_extends: demeomods:.github/release-drafter.yaml
name-template: 'Highlighter v$RESOLVED_VERSION'
tag-template: 'highlighter-v$RESOLVED_VERSION'
tag-prefix: 'highlighter-v'
include-labels: ['area: highlighter']
