_extends: demeomods:.github/release-drafter.yaml
name-template: 'HouseRules v$RESOLVED_VERSION'
tag-template: 'houserules-v$RESOLVED_VERSION'
tag-prefix: 'houserules-v'
include-labels:
  - 'area: houserules/configuration'
  - 'area: houserules/core'
  - 'area: houserules/essentials'
template: |
  $CHANGES

  ---

  ### How To Install

  > [!IMPORTANT]
  > First, make sure you have installed either one of two modloaders: BepInEx or MelonLoader.
  > If you have not, [go here for instructions on how to do that first](https://github.com/orendain/demeomods/blob/main/README.md#installing-a-modloader).

  <details>
  <summary><b>If you have BepInEx</b></summary><p></p>

  Download the ZIP file ending in `.BepInEx.zip` below and extract all folders into Demeo's root game directory.  The folders in the ZIP file should merge with existing folders.
  </details>

  <details>
  <summary><b>If you have MelonLoader</b></summary><p></p>

  Download the ZIP file ending in `.MelonLoader.zip` below and extract all folders into Demeo's root game directory.  The folders in the ZIP file should merge with existing folders.
  </details>
