name: RoomFinder

on:
  pull_request:
    paths:
      - 'RoomFinder/**'
      - '.github/workflows/roomfinder.yaml'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Add Dependencies
        run: |
          wget -O deps.zip https://gist.github.com/orendain/9053d92b9f3571c619618619665c8cbc/raw/63c8d96e6eb642d540c096f5bb9fb8dbcbe937a7/2025-06-08.zip
          7z x deps.zip -o./libs

      - name: Build BepInEx Plugin
        run: dotnet build RoomFinder/RoomFinder.csproj -c BepInEx -v d

      - name: Build MelonLoader Mod
        run: dotnet build RoomFinder/RoomFinder.csproj -c MelonLoader -v d

      - name: Upload BepInEx DLL
        uses: actions/upload-artifact@v4
        with:
          name: RoomFinder.BIE.dll
          path: RoomFinder/bin/netstandard2.1/RoomFinder.BIE.dll

      - name: Upload MelonLoader DLL
        uses: actions/upload-artifact@v4
        with:
          name: RoomFinder.ML.dll
          path: RoomFinder/bin/netstandard2.1/RoomFinder.ML.dll
