name: RoomCode

on:
  pull_request:
    paths:
      - 'RoomCode/**'
      - '.github/workflows/roomcode.yml'
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Add Build Dependencies
        run: |
          C:\msys64\usr\bin\wget.exe https://gist.github.com/orendain/9053d92b9f3571c619618619665c8cbc/raw/eab432f1b7df70451905531f1e77bb05102747ec/ws.zip
          7z x ws.zip

      - name: Build Project
        run: msbuild -m -v:d -p:Configuration=Release -p:DemeoVrDir="%GITHUB_WORKSPACE%" RoomCode\RoomCode.csproj

      - name: Assemble into Bundle
        run: |
          mkdir Bundle\Mods
          xcopy RoomCode\bin\Release\RoomCode.dll Bundle\Mods

      - name: Upload Bundle
        uses: actions/upload-artifact@v3.1.2
        with:
          name: RoomCode
          path: Bundle\*
