name: SkipIntro

on:
  pull_request:
    paths:
      - 'SkipIntro/**'
      - '.github/workflows/skipintro.yml'
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Add Build Dependencies
        run: |
          C:\msys64\usr\bin\wget.exe https://gist.github.com/orendain/9053d92b9f3571c619618619665c8cbc/raw/601ee2ff5f7e7ca8b1946a239bb8c8b68c440a76/2023-09-07.zip
          7z x ws.zip

      - name: Build Project
        run: msbuild -m -v:d -p:Configuration=Release -p:DemeoVrDir="%GITHUB_WORKSPACE%" SkipIntro\SkipIntro.csproj

      - name: Assemble into Bundle
        run: |
          mkdir Bundle\Mods
          xcopy SkipIntro\bin\Release\SkipIntro.dll Bundle\Mods

      - name: Upload Bundle
        uses: actions/upload-artifact@v3
        with:
          name: SkipIntro
          path: Bundle\*
